In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("DataCoSupplyChainDataset.csv", encoding='latin1')

In [5]:
pd.set_option('display.max_columns', None)

In [6]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Id,Customer Lname,Customer Password,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Cally,20755,Holloway,XXXXXXXXX,Consumer,PR,5365 Noble Nectar Island,725.0,2,Fitness,18.251453,-66.037056,Pacific Asia,Bekasi,Indonesia,20755,1/31/2018 22:56,77202,1360,13.110000,0.04,180517,327.75,0.29,1,327.75,314.640015,91.250000,Southeast Asia,Java Occidental,COMPLETE,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Irene,19492,Luna,XXXXXXXXX,Consumer,PR,2679 Rustic Loop,725.0,2,Fitness,18.279451,-66.037064,Pacific Asia,Bikaner,India,19492,1/13/2018 12:27,75939,1360,16.389999,0.05,179254,327.75,-0.80,1,327.75,311.359985,-249.089996,South Asia,Rajastán,PENDING,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,XXXXXXXXX,Gillian,19491,Maldonado,XXXXXXXXX,Consumer,CA,8510 Round Bear Gate,95125.0,2,Fitness,37.292233,-121.881279,Pacific Asia,Bikaner,India,19491,1/13/2018 12:06,75938,1360,18.030001,0.06,179253,327.75,-0.80,1,327.75,309.720001,-247.779999,South Asia,Rajastán,CLOSED,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,XXXXXXXXX,Tana,19490,Tate,XXXXXXXXX,Home Office,CA,3200 Amber Bend,90027.0,2,Fitness,34.125946,-118.291016,Pacific Asia,Townsville,Australia,19490,1/13/2018 11:45,75937,1360,22.940001,0.07,179252,327.75,0.08,1,327.75,304.809998,22.860001,Oceania,Queensland,COMPLETE,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Orli,19489,Hendricks,XXXXXXXXX,Corporate,PR,8671 Iron Anchor Corners,725.0,2,Fitness,18.253769,-66.037048,Pacific Asia,Townsville,Australia,19489,1/13/2018 11:24,75936,1360,29.500000,0.09,179251,327.75,0.45,1,327.75,298.250000,134.210007,Oceania,Queensland,PENDING_PAYMENT,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [9]:
df.describe()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,Longitude,Order Customer Id,Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Price,Product Status
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180516.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,24840.000000,180519.000000,180519.000000,0.0,180519.000000,180519.0
mean,3.497654,2.931847,21.974989,183.107609,0.548291,31.851451,6691.379495,35921.126914,5.443460,29.719955,-84.915675,6691.379495,36221.894903,692.509764,20.664741,0.101668,90260.000000,141.232550,0.120647,2.127638,203.772096,183.107609,21.974989,55426.132327,692.509764,31.851451,NaN,141.232550,0.0
std,1.623722,1.374449,104.433526,120.043670,0.497664,15.640064,4162.918106,37542.461122,1.629246,9.813646,21.433241,4162.918106,21045.379569,336.446807,21.800901,0.070415,52111.490959,139.732492,0.466796,1.453451,132.273077,120.043670,104.433526,31919.279101,336.446807,15.640064,NaN,139.732492,0.0
min,0.000000,0.000000,-4274.979980,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,-33.937553,-158.025986,1.000000,1.000000,19.000000,0.000000,0.000000,1.000000,9.990000,-2.750000,1.000000,9.990000,7.490000,-4274.979980,1040.000000,19.000000,2.000000,NaN,9.990000,0.0
25%,2.000000,2.000000,7.000000,104.379997,0.000000,18.000000,3258.500000,725.000000,4.000000,18.265432,-98.446312,3258.500000,18057.000000,403.000000,5.400000,0.040000,45130.500000,50.000000,0.080000,1.000000,119.980003,104.379997,7.000000,23464.000000,403.000000,18.000000,NaN,50.000000,0.0
50%,3.000000,4.000000,31.520000,163.990005,1.000000,29.000000,6457.000000,19380.000000,5.000000,33.144863,-76.847908,6457.000000,36140.000000,627.000000,14.000000,0.100000,90260.000000,59.990002,0.270000,1.000000,199.919998,163.990005,31.520000,59405.000000,627.000000,29.000000,NaN,59.990002,0.0
75%,5.000000,4.000000,64.800003,247.399994,1.000000,45.000000,9779.000000,78207.000000,7.000000,39.279617,-66.370583,9779.000000,54144.000000,1004.000000,29.990000,0.160000,135389.500000,199.990005,0.360000,3.000000,299.950012,247.399994,64.800003,90008.000000,1004.000000,45.000000,NaN,199.990005,0.0
max,6.000000,4.000000,911.799988,1939.989990,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,115.263077,20757.000000,77204.000000,1363.000000,500.000000,0.250000,180519.000000,1999.989990,0.500000,5.000000,1999.989990,1939.989990,911.799988,99301.000000,1363.000000,76.000000,NaN,1999.989990,0.0

In [ ]:
df.drop(columns=[''], axis=1)

In [11]:
categorical_columns = df.select_dtypes(include='object').columns.tolist()

C:\Users\TGX-100\AppData\Local\Temp\ipykernel_7324\790265440.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include='object').columns.tolist()

In [14]:
for col in categorical_columns:
    print(col+"\n")
    print("Unique values: \n")
    print(df[col].unique())
    print("\nValue count: \n")
    print(df[col].value_counts())
    print("*"*50)

Type

Unique values:

<StringArray>
['DEBIT', 'TRANSFER', 'CASH', 'PAYMENT']
Length: 4, dtype: str

Value count:

Type
DEBIT       69295
TRANSFER    49883
PAYMENT     41725
CASH        19616
Name: count, dtype: int64
**************************************************
Delivery Status

Unique values:

<StringArray>
['Advance shipping', 'Late delivery', 'Shipping on time', 'Shipping canceled']
Length: 4, dtype: str

Value count:

Delivery Status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64
**************************************************
Category Name

Unique values:

<StringArray>
[      'Sporting Goods',               'Cleats',        'Shop By Sport',
      'Women's Apparel',          'Electronics',         'Boxing & MMA',
     'Cardio Equipment',             'Trade-In',     'Kids' Golf Clubs',
   'Hunting & Shooting',  'Baseball & Softball',       'Men's Footwear',
     'Camping & Hiking', 'Consumer Electronics',             'Cameras ',
            'Computers',           'Basketball',               'Soccer',
       'Girls' Apparel',          'Accessories',     'Women's Clothing',
               'Crafts',       'Men's Clothing',     'Tennis & Racquet',
  'Fitness Accessories',      'As Seen on  TV!',           'Golf Balls',
    'Strength Training',  'Children's Clothing',             'Lacrosse',
                'Baby ',              'Fishing',               'Books ',
                 'DVDs',                 'CDs ',               'Garden',
               'Hockey',         'Pet Supplies',    'Health and Beauty',
                'Music',          'Video Games',          'Golf Gloves',
    'Golf Bags & Carts',           'Golf Shoes',         'Golf Apparel',
   'Women's Golf Clubs',     'Men's Golf Clubs',                 'Toys',
         'Water Sports', 'Indoor/Outdoor Games']
Length: 50, dtype: str

Value count:

Category Name
Cleats                  24551
Men's Footwear          22246
Women's Apparel         21035
Indoor/Outdoor Games    19298
Fishing                 17325
Water Sports            15540
Camping & Hiking        13729
Cardio Equipment        12487
Shop By Sport           10984
Electronics              3156
Accessories              1780
Golf Balls               1475
Girls' Apparel           1201
Golf Gloves              1070
Trade-In                  974
Video Games               838
Children's Clothing       652
Women's Clothing          650
Baseball & Softball       632
Hockey                    614
Cameras                   592
Toys                      529
Golf Shoes                524
Pet Supplies              492
Crafts                    484
Garden                    484
DVDs                      483
Computers                 442
Golf Apparel              441
Hunting & Shooting        440
Music                     434
Consumer Electronics      431
Boxing & MMA              423
Books                     405
Kids' Golf Clubs          384
Health and Beauty         362
Sporting Goods            357
Lacrosse                  343
Tennis & Racquet          328
Fitness Accessories       309
Men's Golf Clubs          283
CDs                       271
Men's Clothing            208
Baby                      207
Women's Golf Clubs        181
Soccer                    138
Strength Training         111
As Seen on  TV!            68
Basketball                 67
Golf Bags & Carts          61
Name: count, dtype: int64
**************************************************
Customer City

Unique values:

<StringArray>
[     'Caguas',    'San Jose', 'Los Angeles',   'Tonawanda',       'Miami',
   'San Ramon',    'Freeport',     'Salinas',     'Peabody',   'Canovanas',
 ...
   'Morganton',   'Vacaville',      'Malden',   'Gwynn Oak',    'Toa Baja',
     'Taunton',    'Freehold',      'Sumner',  'Wilmington',          'CA']
Length: 563, dtype: str

Value count:

Customer City
Caguas         66770
Chicago         3885
Los Angeles     3417
Brooklyn        3412
New York        1816
               ...
Bartlett          25
Ponce             22
Malden            22
Freehold          13
CA                 3
Name: count, Length: 563, dtype: int64
**************************************************
Customer Country

Unique values:

<StringArray>
['Puerto Rico', 'EE. UU.']
Length: 2, dtype: str

Value count:

Customer Country
EE. UU.        111146
Puerto Rico     69373
Name: count, dtype: int64
**************************************************
Customer Email

Unique values:

<StringArray>
['XXXXXXXXX']
Length: 1, dtype: str

Value count:

Customer Email
XXXXXXXXX    180519
Name: count, dtype: int64
**************************************************
Customer Fname

Unique values:

<StringArray>
[    'Cally',     'Irene',   'Gillian',      'Tana',      'Orli',  'Kimberly',
 'Constance',     'Erica',   'Nichole',     'Oprah',
 ...
     'Danna',     'Fiora',       'Jay',     'Asley',      'Clau',        'Le',
      'Huff',    'Beatty',     'Paola',     'Brees']
Length: 782, dtype: str

Value count:

Customer Fname
Mary       65150
James       1835
Robert      1759
Michael     1680
David       1625
           ...
Le             1
Huff           1
Beatty         1
Paola          1
Brees          1
Name: count, Length: 782, dtype: int64
**************************************************
Customer Lname

Unique values:

<StringArray>
[ 'Holloway',      'Luna', 'Maldonado',      'Tate', 'Hendricks',   'Flowers',
   'Terrell',   'Stevens',     'Olsen',  'Delacruz',
 ...
      'Cash',  'Domingue',      'Kime',       'Mit',  'Lanister',   'Guevara',
    'Alexan',     'Kiney',     'Delan',     'Harri']
Length: 1110, dtype: str

Value count:

Customer Lname
Smith       64104
Johnson       989
Brown         909
Williams      869
Jones         859
            ...
Guevara         1
Alexan          1
Kiney           1
Delan           1
Harri           1
Name: count, Length: 1109, dtype: int64
**************************************************
Customer Password

Unique values:

<StringArray>
['XXXXXXXXX']
Length: 1, dtype: str

Value count:

Customer Password
XXXXXXXXX    180519
Name: count, dtype: int64
**************************************************
Customer Segment

Unique values:

<StringArray>
['Consumer', 'Home Office', 'Corporate']
Length: 3, dtype: str

Value count:

Customer Segment
Consumer       93504
Corporate      54789
Home Office    32226
Name: count, dtype: int64
**************************************************
Customer State

Unique values:

<StringArray>
[   'PR',    'CA',    'NY',    'FL',    'MA',    'IL',    'MT',    'PA',
    'MI',    'TX',    'DE',    'GA',    'MD',    'OH',    'HI',    'NJ',
    'WI',    'AZ',    'CO',    'MN',    'NC',    'NM',    'OR',    'SC',
    'VA',    'UT',    'WA',    'KY',    'WV',    'RI',    'CT',    'LA',
    'TN',    'DC',    'ND',    'MO',    'IN',    'ID',    'NV',    'KS',
    'AR',    'OK',    'AL',    'IA', '95758', '91732']
Length: 46, dtype: str

Value count:

Customer State
PR       69373
CA       29223
NY       11327
TX        9103
IL        7631
FL        5456
OH        4095
PA        3824
MI        3804
NJ        3191
AZ        3026
GA        2503
MD        2415
NC        1992
CO        1914
VA        1849
OR        1668
MA        1607
TN        1582
NV        1440
MO        1354
HI        1248
CT        1094
UT         968
NM         949
LA         948
WA         920
WI         850
MN         672
SC         665
IN         581
DC         579
KY         487
KS         458
DE         269
RI         243
WV         241
OK         232
ND         215
ID         167
AR         164
MT          87
IA          67
AL          35
95758        2
91732        1
Name: count, dtype: int64
**************************************************
Customer Street

Unique values:

<StringArray>
['5365 Noble Nectar Island',         '2679 Rustic Loop',
     '8510 Round Bear Gate',          '3200 Amber Bend',
 '8671 Iron Anchor Corners',         '2122 Hazy Corner',
     '1879 Green Pine Bank',      '7595 Cotton Log Row',
         '2051 Dusty Route',  '9139 Blue Blossom Court',
 ...
      '5835 Harvest Vista ',         '7798 Lost Front ',
       '2236 Silent Close ',        '7598 Little Maze ',
      '8044 Merry Landing ',     '1799 Cinder Estates ',
        '8333 Red Passage ',            '245 Lost Way ',
       '2455 Merry Hollow ',       '8621 Broad Forest ']
Length: 7458, dtype: str

Value count:

Customer Street
9126 Wishing Expressway     122
4388 Burning Goose Ridge    117
4720 Noble Hills Wynd       116
2878 Hazy Wagon  Thicket    113
398 Emerald Grove           109
                           ...
1799 Cinder Estates           1
8333 Red Passage              1
245 Lost Way                  1
2455 Merry Hollow             1
8621 Broad Forest             1
Name: count, Length: 7458, dtype: int64
**************************************************
Department Name

Unique values:

<StringArray>
[           'Fitness',            'Apparel',               'Golf',
           'Footwear',           'Outdoors',           'Fan Shop',
         'Technology',          'Book Shop',         'Discs Shop',
           'Pet Shop', 'Health and Beauty ']
Length: 11, dtype: str

Value count:

Department Name
Fan Shop              66861
Apparel               48998
Golf                  33220
Footwear              14525
Outdoors               9686
Fitness                2479
Discs Shop             2026
Technology             1465
Pet Shop                492
Book Shop               405
Health and Beauty       362
Name: count, dtype: int64
**************************************************
Market

Unique values:

<StringArray>
['Pacific Asia', 'USCA', 'Africa', 'Europe', 'LATAM']
Length: 5, dtype: str

Value count:

Market
LATAM           51594
Europe          50252
Pacific Asia    41260
USCA            25799
Africa          11614
Name: count, dtype: int64
**************************************************
Order City

Unique values:

<StringArray>
[      'Bekasi',      'Bikaner',   'Townsville',    'Toowoomba',
    'Guangzhou',        'Tokio',       'Manado',       'Sangli',
         'Seúl',     'Jabalpur',
 ...
      'Tottori', 'Rondonópolis',      'Yucaipa',    'Volksrust',
       'Anglet',      'Urganch',  'Pico Rivera',     'Tongling',
      'Liuyang',       'Nashua']
Length: 3597, dtype: str

Value count:

Order City
Santo Domingo           2211
New York City           2202
Los Angeles             1845
Tegucigalpa             1783
Managua                 1682
                        ...
Limbe                      1
Campo Limpo Paulista       1
Tottori                    1
Yucaipa                    1
Pico Rivera                1
Name: count, Length: 3597, dtype: int64
**************************************************
Order Country

Unique values:

<StringArray>
[          'Indonesia',               'India',           'Australia',
               'China',               'Japón',       'Corea del Sur',
            'Singapur',             'Turquía',            'Mongolia',
      'Estados Unidos',
 ...
           'Eslovenia', 'República de Gambia',            'Botsuana',
             'Armenia',   'Guinea Ecuatorial',              'Kuwait',
               'Bután',                'Chad',              'Serbia',
   'Sáhara Occidental']
Length: 164, dtype: str

Value count:

Order Country
Estados Unidos       24840
Francia              13222
México               13172
Alemania              9564
Australia             8497
                     ...
Guinea Ecuatorial        2
Kuwait                   2
Sáhara Occidental        2
Burundi                  1
Serbia                   1
Name: count, Length: 164, dtype: int64
**************************************************
order date (DateOrders)

Unique values:

<StringArray>
['1/31/2018 22:56', '1/13/2018 12:27', '1/13/2018 12:06', '1/13/2018 11:45',
 '1/13/2018 11:24', '1/13/2018 11:03', '1/13/2018 10:42', '1/13/2018 10:21',
 '1/13/2018 10:00',  '1/13/2018 9:39',
 ...
 '1/30/2016 21:10',  '1/30/2016 2:36', '1/29/2016 17:29', '1/29/2016 14:41',
  '1/27/2016 6:59', '1/26/2016 19:25',  '1/22/2016 6:49',  '1/21/2016 2:47',
  '1/20/2016 7:10',  '1/17/2016 5:56']
Length: 65752, dtype: str

Value count:

order date (DateOrders)
10/25/2016 14:39    5
3/30/2016 4:37      5
11/28/2016 1:18     5
9/8/2015 12:15      5
8/4/2017 2:31       5
                   ..
1/27/2016 6:59      1
1/26/2016 19:25     1
1/22/2016 6:49      1
1/20/2016 7:10      1
1/17/2016 5:56      1
Name: count, Length: 65752, dtype: int64
**************************************************
Order Region

Unique values:

<StringArray>
[ 'Southeast Asia',      'South Asia',         'Oceania',    'Eastern Asia',
       'West Asia',    'West of USA ',      'US Center ',     'West Africa',
  'Central Africa',    'North Africa',  'Western Europe', 'Northern Europe',
 'Central America',       'Caribbean',   'South America',     'East Africa',
 'Southern Europe',     'East of USA',          'Canada', 'Southern Africa',
    'Central Asia',  'Eastern Europe',  'South of  USA ']
Length: 23, dtype: str

Value count:

Order Region
Central America    28341
Western Europe     27109
South America      14935
Oceania            10148
Northern Europe     9792
Southeast Asia      9539
Southern Europe     9431
Caribbean           8318
West of USA         7993
South Asia          7731
Eastern Asia        7280
East of USA         6915
West Asia           6009
US Center           5887
South of  USA       4045
Eastern Europe      3920
West Africa         3696
North Africa        3232
East Africa         1852
Central Africa      1677
Southern Africa     1157
Canada               959
Central Asia         553
Name: count, dtype: int64
**************************************************
Order State

Unique values:

<StringArray>
[      'Java Occidental',              'Rajastán',            'Queensland',
             'Guangdong',                 'Tokio', 'Célebes Septentrional',
           'Maharashtra',                  'Seúl',        'Madhya Pradesh',
              'Victoria',
 ...
              'El Aaiún',             'Terranova',            'Zagrebacka',
                'Bitola',        'Haut-Sassandra',               'Savanes',
                 'Düzce',       'Bistrita-Nasaud',               'Tottori',
               'Khorezm']
Length: 1089, dtype: str

Value count:

Order State
Inglaterra                     6722
California                     4966
Isla de Francia                4580
Renania del Norte-Westfalia    3303
San Salvador                   3055
                               ...
Terranova                         1
Bitola                            1
Savanes                           1
Bistrita-Nasaud                   1
Tottori                           1
Name: count, Length: 1089, dtype: int64
**************************************************
Order Status

Unique values:

<StringArray>
[       'COMPLETE',         'PENDING',          'CLOSED', 'PENDING_PAYMENT',
        'CANCELED',      'PROCESSING', 'SUSPECTED_FRAUD',         'ON_HOLD',
  'PAYMENT_REVIEW']
Length: 9, dtype: str

Value count:

Order Status
COMPLETE           59491
PENDING_PAYMENT    39832
PROCESSING         21902
PENDING            20227
CLOSED             19616
ON_HOLD             9804
SUSPECTED_FRAUD     4062
CANCELED            3692
PAYMENT_REVIEW      1893
Name: count, dtype: int64
**************************************************
Product Image

Unique values:

<StringArray>
[                                               'http://images.acmesports.sports/Smart+watch ',
                            'http://images.acmesports.sports/Perfect+Fitness+Perfect+Rip+Deck',
      'http://images.acmesports.sports/Under+Armour+Girls%27+Toddler+Spine+Surge+Running+Shoe',
                      'http://images.acmesports.sports/Nike+Men%27s+Dri-FIT+Victory+Golf+Polo',
                'http://images.acmesports.sports/Under+Armour+Men%27s+Compression+EV+SL+Slide',
          'http://images.acmesports.sports/Under+Armour+Women%27s+Micro+G+Skulpt+Running+Shoe',
                       'http://images.acmesports.sports/Nike+Men%27s+Free+5.0%2B+Running+Shoe',
        'http://images.acmesports.sports/Glove+It+Women%27s+Mod+Oval+3-Zip+Carry+All+Golf+Bag',
  'http://images.acmesports.sports/Bridgestone+e6+Straight+Distance+NFL+San+Diego+Chargers...',
                   'http://images.acmesports.sports/Columbia+Men%27s+PFG+Anchor+Tough+T-Shirt',
 ...
                         'http://images.acmesports.sports/TaylorMade+White+Smoke+IN-12+Putter',
 'http://images.acmesports.sports/Cleveland+Golf+Collegiate+My+Custom+Wedge+588+RTX+Forged...',
            'http://images.acmesports.sports/Merrell+Men%27s+All+Out+Flash+Trail+Running+Shoe',
     'http://images.acmesports.sports/Merrell+Women%27s+Grassbow+Sport+Waterproof+Hiking+Shoe',
          'http://images.acmesports.sports/Merrell+Women%27s+Siren+Mid+Waterproof+Hiking+Boot',
                'http://images.acmesports.sports/Merrell+Women%27s+Grassbow+Sport+Hiking+Shoe',
                                                       'http://images.acmesports.sports/Toys ',
                                 'http://images.acmesports.sports/Pelican+Sunstream+100+Kayak',
                                 'http://images.acmesports.sports/Pelican+Maverick+100X+Kayak',
                        'http://images.acmesports.sports/O%27Brien+Men%27s+Neoprene+Life+Vest']
Length: 118, dtype: str

Value count:

Product Image
http://images.acmesports.sports/Perfect+Fitness+Perfect+Rip+Deck                                 24515
http://images.acmesports.sports/Nike+Men%27s+CJ+Elite+2+TD+Football+Cleat                        22246
http://images.acmesports.sports/Nike+Men%27s+Dri-FIT+Victory+Golf+Polo                           21035
http://images.acmesports.sports/O%27Brien+Men%27s+Neoprene+Life+Vest                             19298
http://images.acmesports.sports/Field+%26+Stream+Sportsman+16+Gun+Fire+Safe                      17325
                                                                                                 ...
http://images.acmesports.sports/Stiga+Master+Series+ST3100+Competition+Indoor+Table+Tennis...       27
http://images.acmesports.sports/SOLE+E35+Elliptical                                                 15
http://images.acmesports.sports/Bushnell+Pro+X7+Jolt+Slope+Rangefinder                              11
http://images.acmesports.sports/SOLE+E25+Elliptical                                                 10
http://images.acmesports.sports/Bowflex+SelectTech+1090+Dumbbells                                   10
Name: count, Length: 118, dtype: int64
**************************************************
Product Name

Unique values:

<StringArray>
[                                 'Smart watch ',
              'Perfect Fitness Perfect Rip Deck',
 'Under Armour Girls' Toddler Spine Surge Runni',
          'Nike Men's Dri-FIT Victory Golf Polo',
    'Under Armour Men's Compression EV SL Slide',
 'Under Armour Women's Micro G Skulpt Running S',
             'Nike Men's Free 5.0+ Running Shoe',
 'Glove It Women's Mod Oval 3-Zip Carry All Gol',
 'Bridgestone e6 Straight Distance NFL San Dieg',
       'Columbia Men's PFG Anchor Tough T-Shirt',
 ...
           'TaylorMade White Smoke IN-12 Putter',
 'Cleveland Golf Collegiate My Custom Wedge 588',
 'Merrell Men's All Out Flash Trail Running Sho',
 'Merrell Women's Grassbow Sport Waterproof Hik',
 'Merrell Women's Siren Mid Waterproof Hiking B',
    'Merrell Women's Grassbow Sport Hiking Shoe',
                                         'Toys ',
                   'Pelican Sunstream 100 Kayak',
                   'Pelican Maverick 100X Kayak',
              'O'Brien Men's Neoprene Life Vest']
Length: 118, dtype: str

Value count:

Product Name
Perfect Fitness Perfect Rip Deck                 24515
Nike Men's CJ Elite 2 TD Football Cleat          22246
Nike Men's Dri-FIT Victory Golf Polo             21035

In [17]:
df.drop(columns=['Customer Email', 'Customer Password','Customer Fname','Customer Lname','Customer Street','Product Image','Product Name'])

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Id,Customer Segment,Customer State,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,20755,Consumer,PR,725.0,2,Fitness,18.251453,-66.037056,Pacific Asia,Bekasi,Indonesia,20755,1/31/2018 22:56,77202,1360,13.110000,0.04,180517,327.750000,0.29,1,327.750000,314.640015,91.250000,Southeast Asia,Java Occidental,COMPLETE,NaN,1360,73,NaN,327.750000,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,19492,Consumer,PR,725.0,2,Fitness,18.279451,-66.037064,Pacific Asia,Bikaner,India,19492,1/13/2018 12:27,75939,1360,16.389999,0.05,179254,327.750000,-0.80,1,327.750000,311.359985,-249.089996,South Asia,Rajastán,PENDING,NaN,1360,73,NaN,327.750000,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,19491,Consumer,CA,95125.0,2,Fitness,37.292233,-121.881279,Pacific Asia,Bikaner,India,19491,1/13/2018 12:06,75938,1360,18.030001,0.06,179253,327.750000,-0.80,1,327.750000,309.720001,-247.779999,South Asia,Rajastán,CLOSED,NaN,1360,73,NaN,327.750000,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,19490,Home Office,CA,90027.0,2,Fitness,34.125946,-118.291016,Pacific Asia,Townsville,Australia,19490,1/13/2018 11:45,75937,1360,22.940001,0.07,179252,327.750000,0.08,1,327.750000,304.809998,22.860001,Oceania,Queensland,COMPLETE,NaN,1360,73,NaN,327.750000,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,19489,Corporate,PR,725.0,2,Fitness,18.253769,-66.037048,Pacific Asia,Townsville,Australia,19489,1/13/2018 11:24,75936,1360,29.500000,0.09,179251,327.750000,0.45,1,327.750000,298.250000,134.210007,Oceania,Queensland,PENDING_PAYMENT,NaN,1360,73,NaN,327.750000,0,1/15/2018 11:24,Standard Class
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,CASH,4,4,40.000000,399.980011,Shipping on time,0,45,Fishing,Brooklyn,EE. UU.,1005,Home Office,NY,11207.0,7,Fan Shop,40.640930,-73.942711,Pacific Asia,Shanghái,China,1005,1/16/2016 3:40,26043,1004,0.000000,0.00,65177,399.980011,0.10,1,399.980011,399.980011,40.000000,Eastern Asia,Shanghái,CLOSED,NaN,1004,45,NaN,399.980011,0,1/20/2016 3:40,Standard Class
180515,DEBIT,3,2,-613.770019,395.980011,Late delivery,1,45,Fishing,Bakersfield,EE. UU.,9141,Corporate,CA,93304.0,7,Fan Shop,35.362545,-119.018700,Pacific Asia,Hirakata,Japón,9141,1/16/2016 1:34,26037,1004,4.000000,0.01,65161,399.980011,-1.55,1,399.980011,395.980011,-613.770019,Eastern Asia,Osaka,COMPLETE,NaN,1004,45,NaN,399.980011,0,1/19/2016 1:34,Second Class
180516,TRANSFER,5,4,141.110001,391.980011,Late delivery,1,45,Fishing,Bristol,EE. UU.,291,Corporate,CT,6010.0,7,Fan Shop,41.629959,-72.967155,Pacific Asia,Adelaide,Australia,291,1/15/2016 21:00,26024,1004,8.000000,0.02,65129,399.980011,0.36,1,399.980011,391.980011,141.110001,Oceania,Australia del Sur,PENDING,NaN,1004,45,NaN,399.980011,0,1/20/2016 21:00,Standard Class
180517,PAYMENT,3,4,186.229996,387.980011,Advance shipping,0,45,Fishing,Caguas,Puerto Rico,2813,Consumer,PR,725.0,7,Fan Shop,18.213350,-66.370575,Pacific Asia,Adelaide,Australia,2813,1/15/2016 20:18,26022,1004,12.000000,0.03,65126,399.980011,0.48,1,399.980011,387.980011,186.229996,Oceania,Australia del Sur,PENDING_PAYMENT,NaN,1004,45,NaN,399.980011,0,1/18/2016 20:18,Standard Class
180518,PAYMENT,4,4,168.949997,383.980011,Shipping on time,0,45,Fishing,Caguas,Puerto Rico,7547,Consumer,PR,725.0,7,Fan Shop,18.290380,-66.370613,Pacific Asia,Nagercoil,India,7547,1/15/2016 18:54,26018,1004,16.000000,0.04,65113,399.980011,0.44,1,399.980011,383.980011,168.949997,South Asia,Tamil Nadu,PENDING_PAYMENT,NaN,1004,45,NaN,399.980011,0,1/19/2016 18:54,Standard Class

In [19]:
df.isnull().sum()

Type                                  0
Days for shipping (real)              0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Fname                        0
Customer Id                           0
Customer Lname                        8
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Customer Zipcode                      3
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Order Country                         0
Order Customer Id                     0
order date (DateOrders)               0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Profit Per Order                0
Order Region                          0
Order State                           0
Order Status                          0
Order Zipcode                    155679
Product Card Id                       0
Product Category Id                   0
Product Description              180519
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64